### ISSUE TITLE
Build fails with qt 5.14

### ISSUE THREAD

**Issue by rezso** [lxqt/compton-conf#146]
../compton-conf.cpp: In function ‘int main(int, char**)’:
../compton-conf.cpp:29:102: error: ‘QString::QString(const char*)’ is private within this context

Same error in maindialog.cpp:

../maindialog.cpp: In constructor ‘MainDialog::MainDialog(QString)’:
../maindialog.cpp:44:48: error: ‘QString& QString::operator=(const QByteArray&)’ is private within this context

Qt 5.14.1
libqtxdg 3.5.0
 lxqt-build-tools 0.7.0

**Comment by tsujan** [comment]
Because I forgot to release it. Will do it soon. Thanks for the report!

**Comment by tsujan** [comment]
Done: https://github.com/lxqt/compton-conf/releases/tag/0.15.0

I admit that I didn't know compton-conf was still a part of LXQt (compton isn't developed and is being replaced by [picom](https://github.com/yshui/picom)).

**Comment by AlfredoRamos** [comment]
@tsujan was the GPG key uploaded to any server?

I can't find your key (0xBE793007AD22DF7E) in any server like pgp.mit.edu

I maintain the AUR package and I can't verify the tarball with GPG because of it.

**Comment by tsujan** [comment]
@AlfredoRamos 
Yes, it's in my GitHub account.

Get the public key with GitHub's API: https://api.github.com/users/tsujan/gpg_keys, as @yan12125 explained at https://github.com/lxqt/lxqt/issues/1779#issuecomment-619406953.

I might add this info to the documentation we're making because, apparently, most of us didn't know about that API.

**Comment by tsujan** [comment]
This also works: https://github.com/tsujan.gpg

**Comment by AlfredoRamos** [comment]
> I might add this info to the documentation we're making because, apparently, most of us didn't know about that API.

Indeed.

Anyways it would be useful to submit the key to a keyserver, it has the advantage that it will be synced between all keyservers so we can use another in case one of them fails. It would also avoid relying on GitHub.

```shell
gpg --send-keys BE793007AD22DF7E
```

It would also make it possible to import the key using the `--recv-keys` flag without downloading the key first.
