### ISSUE TITLE
Tool no longer creates picom-compatible config files

### ISSUE THREAD

**Issue by Ev1lbl0w** [lxqt/compton-conf#150]
##### Expected Behavior
To be able to create a config file for `picom` using this tool, like I used to to in earlier versions.

##### Current Behavior
`picom` halts when he finds now removed options of the config file, that this tools generates.

##### Context
I use this tool to generate configs for `picom`, as it is the suggested tool on the [Arch wiki](https://wiki.archlinux.org/index.php/Picom). However, after version [8.0](https://github.com/yshui/picom/releases/tag/v8-rc2), some options we're removed from `picom`, making the files generated by this tool crashing `picom`.

Should this tool be able to generate files for `picom`, or is it strictly used for the older `compton`?

##### System Information

* Distribution & Version: Arch Linux *(rolling/bleeding edge)*
* Kernel: 5.6.8
* Qt Version: QT5 5.14 and QT4 4.8.7
* libqtxdg Version: 3.5.0
* lxqt-build-tools Version: 0.7.0
* Package version: 0.15.0

**Comment by tsujan** [comment]
> Should this tool be able to generate files for picom

No, as its name tells. The Arch wiki might have been written when picom's config was compatible with compton's.

picom is being developed, while compton isn't. Neither is a part of LXQt but any compositor can be used with LXQt.

**Comment by wxl** [comment]
Maybe we should get rid of compton-conf from LXQt then?

**Comment by tsujan** [comment]
Some still use compton because it works for them. I think there's no point to releasing compton-conf but there's no harm in keeping it as it is.

**Comment by wxl** [comment]
I hear you, but what I'm talking about is managing expectations. If we have it in our repos, people assume we maintain it and continue to release updates. Given the fact that compton is dead and picom is essentially the future of compton, we either need to decide to adapt to picom or essentially decide that compton-conf is dead, too. Since it sounds like the latter is the case, we should leave a note on the README saying it is deprecated and will not receive further updates.

**Comment by tsujan** [comment]
Yes, a note can be added to README.

**Comment by tsujan** [comment]
BTW, as some who isn't satisfied with less than kwin and thinks about LXQt+Wayland+KWin, I gave picom a try. It was fine with openbox.

**Comment by wxl** [comment]
Yeah I've been meaning for a while to swap over to in Lubuntu.

Speaking of BTWs, I brought the above up to picom and suggested they consider forking compton-conf so they can have a GUI configuration tool.

**Comment by tsujan** [comment]
On the one hand, it'll be great if a dev makes a `picom-conf` based on `compton-conf`. On the other hand, we don't want to imply that LXQt depends on `picom`.

This situation is like that of openbox. The difference is that a WM is necessary, while a good compositor is desirable.

Also, some users may have a WM with its own compositor and, not being familiar with these terms, they may run another compositor like `picom` and break their sessions -- I've seen funny complaints like, "LXQt doesn't work with my graphic card" or "LXQt has screen tearing...".

**Comment by wxl** [comment]
There's a very simple solution to that problem: good documentation!
