### ISSUE TITLE
Should we still release it?

### ISSUE THREAD

**Issue by tsujan** [lxqt/compton-conf#153]
Compton isn't developed anymore and Picom is replacing it for those who want a standalone compositor for Xorg, Should we continue releasing compton-conf?

**Comment by luis-pereira** [comment]
We should stop releasing it.
We should announce it before doing the last release. And then archive it.
There are some new translations that "deserve" to be released. Then archive it.

**Comment by tsujan** [comment]
OK. If someone wants to use it, it can be compiled against the latest LXQt or the old package should work.

**Comment by tsujan** [comment]
And yes, I agree that translations deserve to be released.

**Comment by tsujan** [comment]
Oh, I'd forgotten https://github.com/lxqt/compton-conf/issues/150: we've already announced that it'll receive no more updates.

I'll release 0.16.0. Then we should really forget it.

@stefonarch, please remove it from Weblate if it's there. Manual translations won't be merged either.

**Comment by tsujan** [comment]
OK, the last version (0.16.0) is released and the lack of further updates was announced before. So, it just needs to be made read-only somehow (no PR, no issue opening). I don't know how to do that. Please do it if you know -- there's no haste though.

**Comment by luis-pereira** [comment]
I will add a note pointing to https://github.com/yshui/picom.
And them simply archive it. No PR, read only, but can still be forked.
