### ISSUE TITLE
Missing icon file?

### ISSUE THREAD

**Issue by jubalh** [lxqt/compton-conf#72]
https://github.com/lxqt/compton-conf/blob/master/compton-conf.desktop.in#L8 mentions an icon file.

##### Expected Behavior
Icon file present in repo and being installed via CMake.

##### Current Behavior
AFAIK not getting installed

##### System Information
* Distribution & Version: openSUSE TW
* libqtxgd Version: latest git
* lxqt-build-tools Version: latest git
* Package version: latest git

**Comment by luis-pereira** [comment]
@jubalh The icon is part of the compton package.
https://github.com/chjj/compton/tree/master/media

compton should probably be added as a dependency for compton-conf.

**Comment by jubalh** [comment]
Thanks for the hint @luis-pereira.

Not sure whether it might be a good idea to use different icon so that users can easily differentiate visually.
